### ISSUE TITLE
Strings wrapped in b'' in .csv output

### ISSUE THREAD

**Issue by martinjaeger** [SchrodingersGat/KiBoM#45] opened 2018-10-11 19:26 UTC
Just updated to the most recent version. Unfortunately, it creates a .csv output as follows with the strings wrapped in `b'...'`:
```
Component,Description,Part,References,Value,Footprint,Quantity Per PCB,Datasheet,Manufacturer,PartNumber,Remarks,Alternative,Config,DNP,Supplier
1,b'Unpolarized capacitor',b'C',b'C9 C10 C16 C19 C24 C25 C26 C30 C31 C32 C34 C39 C42',b'100n',b'C_0603_1608',b'13',b'',b'Yageo',b'CC0603KRX7R9BB104',b'',b'',b'',b'',b''
```
Using Python 3.7.0 on Linux.

**Comment by martinjaeger** [comment] 2018-10-14 16:59
Seems to be an issue only with Python 3. Using Python 2 it worked.

**Comment by trentks** [comment] 2018-11-07 01:35
Also the same error, and I can also confirm that running it with python2 produces the expected result.

**Comment by trentks** [comment] 2019-06-27 23:45
@SchrodingersGat

Probably a good idea to implement something like #29, I don't think there's any harm in explicitly calling python2. The script doesn't behave well with python3 and that's the default alias of python in most environments. 

At the very least perhaps the README.md should stress the need for python2, and perhaps `example/html_ex.png` could reflect this.

**Comment by martinjaeger** [comment] 2019-06-28 07:19
Well, as Python 2 reaches its end of life this year and will not be maintained anymore from 2020 on, I think it would be a good idea to support Python 3 instead.

**Comment by trentks** [comment] 2019-06-28 07:30
Fair point @martinjaeger, I do recall having briefly tried to find the cause / debug this some months ago--but I never did get to the bottom of it. I might have another crack at it. This issue is somewhat annoying.

**Comment by SchrodingersGat** [comment] 2019-06-28 10:25
Good points all around. Do either of you have time to look into this? Unfortunately I can't dedicate any time to this right now. I'd be happy to look at a PR :)

**Comment by SchrodingersGat** [comment] 2019-06-30 22:00
Fixed in https://github.com/SchrodingersGat/KiBoM/pull/59

**Closed by SchrodingersGat** 2019-06-30 22:00 UTC
