### ISSUE TITLE
False should not be used in template bom.ini file, as True does not work

### ISSUE THREAD

**Issue by retiredfeline** [SchrodingersGat/KiBoM#165] opened 2022-03-26 23:33 UTC
In a few places in the template bom.ini file, parameters are set to False. This suggests that to negate it, one should use True. But this is not the case, only 1 works. Therefore I suggest all instances of False be changed to 0 to not mislead

```
complex_variant = False
hide_headers = False
hide_pcb_info = False
digikey_link = False
```

**Comment by set-soft** [comment] 2022-03-28 17:08
This is repeated, take a look at #67 
The patch I mention fixes the lack of "True", even when the generated files defaults to 0/1.

**Comment by SchrodingersGat** [comment] 2022-03-28 23:01
Duplicate of https://github.com/SchrodingersGat/KiBoM/issues/67

**Closed by SchrodingersGat** 2022-03-28 23:01 UTC
